apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: gatekeeper
spec:
  audit:
    logLevel: INFO
    replicas: 2
  validatingWebhook: Enabled
  webhook:
    logLevel: INFO
    failurePolicy: Ignore
    emitAdmissionEvents: Enabled
