apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MaxReplicas
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: maxreplicas
spec:
  enforcementAction: deny
  match:
    namespaces:
      - test-with-opa-1
      - test-with-opa-2
    kinds:
      - apiGroups: ["*"]
        kinds: ["Deployment"]
  parameters:
    replicas: 2
